#!/bin/bash
#
# Auto-generated script to fix shell script permissions
# Generated by Windows-to-Mac migration checker
#
# This script safely fixes execute permissions on shell scripts with:
# - Validation of files before modification
# - Backup creation (optional)
# - Detailed logging
# - Error handling
#

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
CREATE_BACKUP=false
BACKUP_DIR="backups/permissions_$(date +%Y%m%d_%H%M%S)"
DRY_RUN=false

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --backup)
            CREATE_BACKUP=true
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --help)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --backup    Create backups of permission states before fixing"
            echo "  --dry-run   Show what would be done without making changes"
            echo "  --help      Show this help message"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

echo -e "${GREEN}Fixing shell script permissions...${NC}"
echo ""

if [ "$DRY_RUN" = true ]; then
    echo -e "${YELLOW}DRY RUN MODE - No changes will be made${NC}"
    echo ""
fi

if [ "$CREATE_BACKUP" = true ] && [ "$DRY_RUN" = false ]; then
    echo "Creating backup directory: $BACKUP_DIR"
    mkdir -p "$BACKUP_DIR"
    echo ""
fi

# Counter for statistics
TOTAL_FILES=0
FIXED_FILES=0
SKIPPED_FILES=0
FAILED_FILES=0

# Function to fix permissions on a file
fix_permissions() {
    local file=$1
    TOTAL_FILES=$((TOTAL_FILES + 1))
    
    # Check if file exists
    if [ ! -f "$file" ]; then
        echo -e "${RED}✗ File not found: $file${NC}"
        FAILED_FILES=$((FAILED_FILES + 1))
        return 1
    fi
    
    # Check current permissions
    current_perms=$(stat -f "%Lp" "$file" 2>/dev/null || stat -c "%a" "$file" 2>/dev/null)
    
    # Check if already executable
    if [ -x "$file" ]; then
        echo -e "${YELLOW}○ Already executable: $file (permissions: $current_perms)${NC}"
        SKIPPED_FILES=$((SKIPPED_FILES + 1))
        return 0
    fi
    
    # Create backup if requested
    if [ "$CREATE_BACKUP" = true ] && [ "$DRY_RUN" = false ]; then
        backup_file="$BACKUP_DIR/$(echo $file | tr '/' '_').perms"
        echo "$file:$current_perms" >> "$BACKUP_DIR/permissions.log"
    fi
    
    # Fix permissions
    if [ "$DRY_RUN" = true ]; then
        echo -e "${GREEN}✓ Would fix: $file (current: $current_perms -> new: 755)${NC}"
    else
        if chmod +x "$file"; then
            new_perms=$(stat -f "%Lp" "$file" 2>/dev/null || stat -c "%a" "$file" 2>/dev/null)
            echo -e "${GREEN}✓ Fixed: $file (permissions: $current_perms -> $new_perms)${NC}"
            FIXED_FILES=$((FIXED_FILES + 1))
        else
            echo -e "${RED}✗ Failed to fix: $file${NC}"
            FAILED_FILES=$((FAILED_FILES + 1))
            return 1
        fi
    fi
    
    return 0
}

# Fix each shell script
echo "Processing shell scripts..."
echo ""

fix_permissions "scripts/cleanup.sh"
fix_permissions "scripts/deploy.sh"
fix_permissions "scripts/list_ssm_parameters.sh"
fix_permissions "scripts/prereq.sh"
fix_permissions "start.sh"

# Print summary
echo ""
echo "=========================================="
echo "Summary:"
echo "=========================================="
echo "Total files processed: $TOTAL_FILES"
if [ "$DRY_RUN" = false ]; then
    echo -e "${GREEN}Fixed: $FIXED_FILES${NC}"
    echo -e "${YELLOW}Already executable: $SKIPPED_FILES${NC}"
    if [ $FAILED_FILES -gt 0 ]; then
        echo -e "${RED}Failed: $FAILED_FILES${NC}"
    fi
else
    echo "Would fix: $FIXED_FILES"
    echo "Already executable: $SKIPPED_FILES"
fi
echo "=========================================="

if [ "$CREATE_BACKUP" = true ] && [ "$DRY_RUN" = false ]; then
    echo ""
    echo "Backup created in: $BACKUP_DIR"
    echo "To restore permissions, use:"
    echo "  while IFS=: read -r file perms; do chmod \$perms \$file; done < $BACKUP_DIR/permissions.log"
fi

if [ "$DRY_RUN" = false ]; then
    echo ""
    echo -e "${GREEN}All permissions fixed successfully!${NC}"
else
    echo ""
    echo -e "${YELLOW}Dry run complete. Run without --dry-run to apply changes.${NC}"
fi

# Exit with error if any files failed
if [ $FAILED_FILES -gt 0 ]; then
    exit 1
fi

exit 0
